import { jsPDF } from 'jspdf';

interface ReportPDFOptions {
  reportName: string;
  coverTitle?: string;
  companyName?: string;
  projectName?: string;
  sections: {
    title: string;
    notes: string;
    photoUrls: string[];
  }[];
}

export async function generateReportPDF(options: ReportPDFOptions): Promise<Blob> {
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  // Cover page
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'bold');
  const titleLines = pdf.splitTextToSize(options.reportName, contentWidth);
  pdf.text(titleLines, pageWidth / 2, pageHeight / 3, { align: 'center' });

  if (options.coverTitle) {
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(100, 100, 100);
    pdf.text(options.coverTitle, pageWidth / 2, pageHeight / 3 + 20, { align: 'center' });
    pdf.setTextColor(0, 0, 0);
  }

  if (options.companyName) {
    pdf.setFontSize(12);
    pdf.setTextColor(130, 130, 130);
    pdf.text(options.companyName, pageWidth / 2, pageHeight / 3 - 20, { align: 'center' });
    pdf.setTextColor(0, 0, 0);
  }

  // Date
  pdf.setFontSize(11);
  pdf.setTextColor(130, 130, 130);
  const dateStr = new Intl.DateTimeFormat('en-US', { year: 'numeric', month: 'long', day: 'numeric' }).format(new Date());
  pdf.text(dateStr, pageWidth / 2, pageHeight / 3 + 40, { align: 'center' });
  pdf.setTextColor(0, 0, 0);

  if (options.projectName) {
    pdf.setFontSize(11);
    pdf.setTextColor(130, 130, 130);
    pdf.text(options.projectName, pageWidth / 2, pageHeight / 3 + 50, { align: 'center' });
    pdf.setTextColor(0, 0, 0);
  }

  // Footer on cover
  pdf.setFontSize(9);
  pdf.setTextColor(180, 180, 180);
  pdf.text('Generated by JobMate', pageWidth / 2, pageHeight - 15, { align: 'center' });
  pdf.setTextColor(0, 0, 0);

  // Section pages (text only - photos require image loading which is complex)
  for (const section of options.sections) {
    pdf.addPage();
    let y = margin;

    // Section title
    if (section.title) {
      pdf.setFontSize(18);
      pdf.setFont('helvetica', 'bold');
      pdf.text(section.title, margin, y + 10);
      y += 20;
    }

    // Horizontal rule
    pdf.setDrawColor(220, 220, 220);
    pdf.setLineWidth(0.5);
    pdf.line(margin, y, pageWidth - margin, y);
    y += 10;

    // Photo count note
    if (section.photoUrls.length > 0) {
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'italic');
      pdf.setTextColor(130, 130, 130);
      pdf.text(`${section.photoUrls.length} photo(s) — view online for full resolution`, margin, y);
      pdf.setTextColor(0, 0, 0);
      y += 10;
    }

    // Notes
    if (section.notes) {
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'normal');
      const noteLines = pdf.splitTextToSize(section.notes, contentWidth);

      for (const line of noteLines) {
        if (y > pageHeight - margin - 10) {
          pdf.addPage();
          y = margin;
        }
        pdf.text(line, margin, y);
        y += 6;
      }
    }

    // Footer
    pdf.setFontSize(9);
    pdf.setTextColor(180, 180, 180);
    pdf.text('Generated by JobMate', pageWidth / 2, pageHeight - 15, { align: 'center' });
    pdf.setTextColor(0, 0, 0);
  }

  return pdf.output('blob');
}
